export enum ProviderTokenEnum {
  DATE_TIME_DEFAULT = 'DATE_TIME_REPOSITORY',

  DATE_TIME_REPOSITORY = 'DATE_TIME_REPOSITORY',
  IDENTIFIER_UUID_NULL_REPOSITORY = 'IDENTIFIER_UUID_NULL_REPOSITORY',
  IDENTIFIER_UUID_REPOSITORY = 'IDENTIFIER_UUID_REPOSITORY',
  SYSTEM_INFO_REPOSITORY = 'SYSTEM_INFO_REPOSITORY',
}
